# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfd1f34a48258fce7ab25e977fe1a42adffd0aa0505eb0b2749c719b7682f4ff91b496f6eba4272d53d288ba72fd9c2a44e452297808484e72a77571971e5723

test:
  secret_key_base: 1ef95e75640e6254eacf928cae6ccc734cd659395a8cf84745446cd0831571cfe79fe1d5d7c005a9fec6eaedf32e6fa6cdef6613181d8722096e38035b37876c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
